export interface PeritagemItemTemplate {
    id: number;
    descricao: string;
}

export const PERITAGEM_CATALOG: PeritagemItemTemplate[] = [
    { id: 1, descricao: 'Porca /Contra porca da Haste - Usinar nova' },
    { id: 2, descricao: 'Porca /Contra porca da Haste - Recuperar/retificar porca' },
    { id: 3, descricao: 'Cabeçote Traseiro - Recuperar aloj. de vedação com a camisa por soldagem/usinagem' },
    { id: 4, descricao: 'Cabeçote Traseiro - Recuperar alojamento da rótula soldagem/usinagem' },
    { id: 5, descricao: 'Cabeçote Traseiro - Fabricar novo cabeçote' },
    { id: 6, descricao: 'Cabeçote Traseiro - Fabricar olhal traseiro' },
    { id: 7, descricao: 'Cabeçote Traseiro - Retificar diâmetros internos' },
    { id: 8, descricao: 'Cabeçote Traseiro - Retificar rosca de alimentação do cabeçote' },
    { id: 9, descricao: 'Cabeçote Traseiro - Retificar face de alimentação do cabeçote' },
    { id: 10, descricao: 'Cabeçote Dianteiro - Recuperar aloj. de vedação com a camisa por soldagem/usinagem' },
    { id: 11, descricao: 'Cabeçote Dianteiro - Fabricar novo cabeçote' },
    { id: 12, descricao: 'Cabeçote Dianteiro - Retificar/recuperar diâmetros internos' },
    { id: 13, descricao: 'Cabeçote Dianteiro - Retificar rosca de alimentação do cabeçote' },
    { id: 14, descricao: 'Cabeçote Dianteiro - Retificar face da alimentação do cabeçote' },
    { id: 15, descricao: 'Olhal Dianteiro - Recuperar furo do olhal por soldagem/usinagem' },
    { id: 16, descricao: 'Olhal Dianteiro - Retificar rosca do olhal da haste' },
    { id: 17, descricao: 'Olhal Dianteiro - Fabricar/substituir olhal' },
    { id: 18, descricao: 'Bucha Olhal Dianteiro - Fabricar/substituir bucha do olhal' },
    { id: 19, descricao: 'Munhão - Recuperar extremidade do munhão por soldagem/usinagem' },
    { id: 20, descricao: 'Munhão - Recuperar extremidade do munhão por metalização' },
    { id: 21, descricao: 'Munhão - Fabricar/substituir munhão rosqueado' },
    { id: 22, descricao: 'Munhão - Fabricar/substituir munhão soldado' },
    { id: 23, descricao: 'Munhão - Retificar/recuperar rosca do munhão' },
    { id: 24, descricao: 'Válvula Amortecimento/partida rápida/Desaeração Dianteiro - Fabricar nova' },
    { id: 25, descricao: 'Válvula Amortecimento/partida rápida/Desaeração Dianteiro - Recuperar/Retificar sede' },
    { id: 26, descricao: 'Válvula Amortecimento/partida rápida/Desaeração Traseiro - Fabricar nova' },
    { id: 27, descricao: 'Válvula Amortecimento/partida rápida/Desaeração Traseiro - Recuperar/Retificar sede' },
    { id: 28, descricao: 'Olhal Traseiro - Recuperar furo do olhal por soldagem/usinagem' },
    { id: 29, descricao: 'Olhal Traseiro - Fabricar/substituir olhal' },
    { id: 30, descricao: 'Porca Munhão - Retificar rosca da porca' },
    { id: 31, descricao: 'Porca Munhão - Fabricar nova porca do munhão' },
    { id: 32, descricao: 'Camisa - Fabricar nova camisa cega' },
    { id: 33, descricao: 'Camisa - Brunir camisa cega' },
    { id: 34, descricao: 'Camisa - Cromar camisa cega' },
    { id: 35, descricao: 'Camisa - Fabricar nova camisa tubo liso' },
    { id: 36, descricao: 'Camisa - Fabricar nova camisa com rebaixo e rosca nas extremidades e rosca do munhão' },
    { id: 37, descricao: 'Camisa - Fabricar nova camisa com rebaixo e rosca nas extremidades' },
    { id: 38, descricao: 'Camisa - Fabricar nova camisa com flanges soldados' },
    { id: 39, descricao: 'Camisa - Brunir camisa' },
    { id: 40, descricao: 'Camisa - Cromar camisa' },
    { id: 41, descricao: 'Camisa - Retificar rosca das extremidades da camisa e fixação do munhão da camisa' },
    { id: 42, descricao: 'Camisa - Retificar/polir diâmetros das extremidades da camisa' },
    { id: 43, descricao: 'Flanges da Camisa - Fabricar novo flange' },
    { id: 44, descricao: 'Flanges da Camisa - Retificar roscas' },
    { id: 45, descricao: 'Êmbolo - Recuperar êmbolo por metalização' },
    { id: 46, descricao: 'Êmbolo - Retificar/polir diâmetros e rosca do êmbolo' },
    { id: 47, descricao: 'Êmbolo - Fabricar novo êmbolo completo' },
    { id: 48, descricao: 'Êmbolo - Fabricar miolo do êmbolo' },
    { id: 49, descricao: 'Espaçador - Fabricar espaçador' },
    { id: 50, descricao: 'Sobreposta - Fabricar nova sobreposta' },
    { id: 51, descricao: 'Sobreposta - Retificar diâmetros da sobreposta' },
    { id: 52, descricao: 'Sobreposta - Recuperar diâmetros da sobreposta por soldagem/usinagem' },
    { id: 53, descricao: 'Fabricar nova Bucha guia' },
    { id: 54, descricao: 'Bucha Guia - Retificar diâmetros da bucha guia' },
    { id: 55, descricao: 'Rótula - Substituir rótula do olhal' },
    { id: 56, descricao: 'Haste - Fabricar/Substituir nova haste' },
    { id: 57, descricao: 'Haste - Cromar haste' },
    { id: 58, descricao: 'Haste - Retificar rosca do olhal' },
    { id: 59, descricao: 'Haste - Recuperar rosca do olhal por soldagem/usinagem' },
    { id: 60, descricao: 'Haste - Recuperar rosca do êmbolo e ponteira de amortecimento por soldagem/usinagem' },
    { id: 61, descricao: 'Haste - Recuperar ponteira de amortecimento por metalização' },
    { id: 62, descricao: 'Porca Amortecimento Traseiro - Retificar/ajustar rosca e diâmetros' },
    { id: 63, descricao: 'Porca Amortecimento Traseiro - Fabricar nova porca' },
    { id: 64, descricao: 'Bucha Amortecimento Traseiro Flutuante - Fabricar nova' },
    { id: 65, descricao: 'Bucha Amortecimento Traseiro Rosqueada - Fabricar nova em aço' },
    { id: 66, descricao: 'Bucha Amortecimento Traseiro Rosqueada - Fabricar nova em Bronze' },
    { id: 67, descricao: 'Bucha Amortecimento Traseiro Rosqueada - Recuperar bucha por metalização' },
    { id: 68, descricao: 'Bucha Amortecimento Dianteiro - Fabricar nova em aço' },
    { id: 69, descricao: 'Bucha Amortecimento Dianteiro - Fabricar nova em Bronze' },
    { id: 70, descricao: 'Bucha Amortecimento Dianteiro - Recuperar bucha por metalização' },
    { id: 71, descricao: 'Kit Vedação - Substituir vedação em Viton conforme especificação ou desenho fornecido' },
    { id: 72, descricao: 'Kit Vedação - Substituir vedação em Borracha Nitrílica conforme especificação ou desenho' },
    { id: 73, descricao: 'Kit Elementos de Fixação (porcas, arruelas, Parafusos, pinos graxeiros, anéis elásticos)' },
    { id: 74, descricao: 'Tirante - Substituir tirante' },
    { id: 75, descricao: 'Tirante - Recuperar roscas' },
    { id: 76, descricao: 'Tomada de Pressão - Substituir tomada de pressão' },
    { id: 77, descricao: 'Proteção sanfonada - Substituir proteção sanfonada em Trevira' },
    { id: 78, descricao: 'Proteção sanfonada - Substituir proteção sanfonada em Fibra de Vidro Aluminizada' },
    { id: 79, descricao: 'Jateamento e Pintura - Realizar jateamento e pintura' },
    { id: 80, descricao: 'Conjunto - Desmontagem e Peritagem' },
    { id: 81, descricao: 'Conjunto - Montagem, Teste e Pintura' },
];
