export const STANDARD_ITEMS = [
    "Porca /Contra porca da Haste - Usinar nova",
    "Porca /Contra porca da Haste - Recuperar/retificar porca",
    "Cabeçote Traseiro - Recuperar aloj. de vedação com a camisa por soldagem/usinagem",
    "Cabeçote Traseiro - Recuperar alojamento da rótula soldagem/usinagem",
    "Cabeçote Traseiro - Fabricar novo cabeçote",
    "Cabeçote Traseiro - Fabricar olhal traseiro",
    "Cabeçote Traseiro - Retificar diâmetros internos",
    "Cabeçote Traseiro - Retificar rosca de alimentação do cabeçote",
    "Cabeçote Traseiro - Retificar face da alimentação do cabeçote",
    "Cabeçote Dianteiro - Recuperar aloj. de vedação com a camisa por soldagem/usinagem",
    "Cabeçote Dianteiro - Fabricar novo cabeçote",
    "Cabeçote Dianteiro - Retificar/recuperar diâmetros internos",
    "Cabeçote Dianteiro - Retificar rosca de alimentação do cabeçote",
    "Cabeçote Dianteiro - Retificar face da alimentação do cabeçote",
    "Olhal Dianteiro - Recuperar furo do olhal por soldagem/usinagem",
    "Olhal Dianteiro - Retificar rosca do olhal da haste",
    "Olhal Dianteiro - Fabricar/substituir olhal",
    "Bucha Olhal Dianteiro - Fabricar/substituir bucha do olhal",
    "Munhão - Recuperar extremidade do munhão por soldagem/usinagem",
    "Munhão - Recuperar extremidade do munhão por metalização",
    "Munhão - Fabricar/substituir munhão rosqueado",
    "Munhão - Fabricar/substituir munhão soldado",
    "Munhão - Retificar/recuperar rosca do munhão",
    "Válvula Amortecimento/partida rápida/Desaeração Dianteiro - Fabricar nova",
    "Válvula Amortecimento/partida rápida/Desaeração Dianteiro - Recuperar/Retificar sede",
    "Válvula Amortecimento/partida rápida/Desaeração Traseiro - Fabricar nova",
    "Válvula Amortecimento/partida rápida/Desaeração Traseiro - Recuperar/Retificar sede",
    "Olhal Traseiro - Recuperar furo do olhal por soldagem/usinagem",
    "Olhal Traseiro - Fabricar/substituir olhal",
    "Porca Munhão - Retificar rosca da porca",
    "Porca Munhão - Fabricar nova porca do munhão",
    "Camisa - Fabricar nova camisa cega",
    "Camisa - Brunir camisa cega",
    "Camisa - Cromar camisa cega",
    "Camisa - Fabricar nova camisa tubo liso",
    "Camisa - Fabricar nova camisa com rebaixo e rosca nas extremidades e rosca do munhão",
    "Camisa - Fabricar nova camisa com rebaixo e rosca nas extremidades",
    "Camisa - Fabricar nova camisa com flanges soldados",
    "Camisa - Brunir camisa",
    "Camisa - Cromar camisa",
    "Camisa - Retificar rosca das extremidades da camisa e fixação do munhão da camisa",
    "Camisa - Retificar/polir diâmetros das extremidades da camisa",
    "Flanges da Camisa - Fabricar novo flange",
    "Flanges da Camisa - Retificar roscas",
    "Êmbolo - Recuperar êmbolo por metalização",
    "Êmbolo - Retificar/polir diâmetros e rosca do êmbolo",
    "Êmbolo - Fabricar novo êmbolo completo",
    "Êmbolo - Fabricar miolo do êmbolo",
    "Espaçador - Fabricar espaçador",
    "Sobreposta - Fabricar nova sobreposta",
    "Sobreposta - Retificar diâmetros da sobreposta",
    "Sobreposta - Recuperar diâmetros da sobreposta por soldagem/usinagem",
    "Fabricar nova Bucha guia",
    "Bucha Guia - Retificar diâmetros da bucha guia",
    "Rótula - Substituir rótula do olhal",
    "Haste - Fabricar/Substituir nova haste",
    "Haste -Cromar haste",
    "Haste - Retificar rosca do olhal",
    "Haste - Recuperar rosca do olhal por soldagem/usinagem",
    "Haste - Recuperar rosca do êmbolo e ponteira de amortecimento por soldagem/usinagem",
    "Haste - Recuperar ponteira de amortecimento por metalização",
    "Porca Amortecimento Traseiro - Retificar/ajustar rosca e diâmetros",
    "Porca Amortecimento Traseiro - Fabricar nova porca",
    "Bucha Amortecimento Traseiro Flutuante - Fabricar nova",
    "Bucha Amortecimento Traseiro Rosqueada - Fabricar nova em aço",
    "Bucha Amortecimento Traseiro Rosqueada - Fabricar nova em Bronze",
    "Bucha Amortecimento Traseiro Rosqueada - Recuperar bucha por metalização",
    "Bucha Amortecimento Dianteiro - Fabricar nova em aço",
    "Bucha Amortecimento Dianteiro - Fabricar nova em Bronze",
    "Bucha Amortecimento Dianteiro - Recuperar bucha por metalização",
    "Kit Vedação - Substituir vedação em Viton conforme especificação ou desenho fornecido",
    "Kit Vedação - Substituir vedação em Borracha Nitrílica conforme especificação ou desenho",
    "Kit Elementos de Fixação (porcas, arruelas, Parafusos, pinos graxeiros, anéis elásticos)",
    "Tirante - Substituir tirante",
    "Tirante - Recuperar roscas",
    "Tomada de Pressão - Substituir tomada de pressão",
    "Proteção sanfonada - Substituir proteção sanfonada em Trevira",
    "Proteção sanfonada - Substituir proteção sanfonada em Fibra de Vidro Aluminizada",
    "Jateamento e Pintura - Realizar jateamento e pintura",
    "Conjunto - Desmontagem e Peritagem",
    "Conjunto - Montagem, Teste e Pintura"
];
