export const USIMINAS_ITEMS = [
    "Desmontar e montar",
    "Jatear e pintar",
    "Realizar teste de perfornance",
    "Data Book",
    "Embalagem",
    "Fornecer Amortecedor Dianteiro",
    "Fornecer Amortecedor Traseiro",
    "Fornecer Bucha olhal",
    "Fornecer Cabeçote Dianteiro",
    "Fornecer Cabeçote Traseiro",
    "Fornecer Bucha Guia",
    "Fornecer Camisa",
    "Fornecer Fixação por Munhão",
    "Fornecer Haste",
    "Fornecer Rótula",
    "Fornecer Embolo",
    "Fornecer Fix. (Aleta macho/fêmea/Base)",
    "Fornecer Kit Vedação Especial Viton",
    "Fornecer Kit Vedação Viton CHEVRON",
    "Fornecer Kit Vedação Padrão Nitrilica",
    "Fornecer Kit Vedação Nitrilica CHEVRON",
    "Fornecer Kit Vedação Padrão Poliuretano",
    "Fornecer Kit Vedação PU CHEVRON",
    "Fornecer Olhal",
    "Fornecer Parafusos",
    "Fornecer proteção Sanfonada Alta Temp.",
    "Fornecer proteção Sanfonada Padrão",
    "Fornecer Sede Amortecedor Dianteiro",
    "Fornecer Sede Amortecedor Traseiro",
    "Fornecer Sobreposta",
    "Fornecer Tirante",
    "Fornecer Válvula de Retenção",
    "Fornecer Válvula Regul. Amortecimento",
    "Realizar desenho completo padrão Usiminas",
    "Reparo parcial Amortecedor Diant.",
    "Reparo parcial Amortecedor Traseiro",
    "Reparo parcial Cabeçote Dianteiro",
    "Reparo parcial Cabeçote Traseiro",
    "Reparo parcial Camisa",
    "Reparo parcial Embolo",
    "Reparo Parcial Fix. Al mach/fêm/Base",
    "Reparo parcial Fixação por Munhão",
    "Reparo parcial Haste",
    "Reparo parcial Olhal",
    "Reparo parcial Rótula",
    "Reparo parcial Sede Amortecedor Diant",
    "Reparo parcial Sede Amortecedor Trase",
    "Reparo parcial Sobreposta",
    "Reparo parcial Vál. Reguladora Amort.",
    "Reparo parcial Válvula de Retenção",
    "Reparo total Amortecedor Dianteiro",
    "Reparo total Amortecedor Traseiro",
    "Reparo total Cabeçote Dianteiro",
    "Reparo total Cabeçote Traseiro",
    "Reparo total Camisa cromo 0,03 a 0,05",
    "Reparo total Camisa cromo 0,06 a 0,09",
    "Reparo total Camisa cromo 0,10 a 0,15",
    "Metalização do Embolo 1,5 a 2,0",
    "Reparo total Êmbolo",
    "Reparo total Fix. Al macho/fêmea/Base",
    "Reparo total Fixação por Munhão",
    "Reparo total Haste cromo 0,03 a 0,05",
    "Reparo total Haste cromo 0,06 a 0,09",
    "Reparo total Haste cromo 0,10 a 0,15",
    "Reparo total Olhal",
    "Reparo total Sede Amortecedor Diant",
    "Reparo total Sede Amortecedor Trase",
    "Reparo total Sobreposta"
];
